trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SnowflakeCredentials  # Link to the variable group

stages:
- stage: InstallSnowCLI
  displayName: Install SnowCLI
  jobs:
  - job: Install
    steps:
    - script: |
        curl -sSL https://github.com/Snowflake-Labs/snowcli/releases/latest/download/install.sh | bash
        snow --version
      displayName: 'Install SnowCLI'

- stage: LoginToSnowflake
  displayName: Login to Snowflake
  dependsOn: InstallSnowCLI
  jobs:
  - job: Login
    steps:
    - script: |
        snow configure --account $(SNOWFLAKE_ACCOUNT) --username $(SNOWFLAKE_USERNAME) --auth-type password
        snow configure set password $(SNOWFLAKE_PASSWORD)
      displayName: 'Login to Snowflake'

- stage: ExecuteSQLScript
  displayName: Execute SQL Script
  dependsOn: LoginToSnowflake
  jobs:
  - job: Execute
    steps:
    - checkout: self  # Pull the code from the repository
    - script: |
        snow sql --file "$(Build.SourcesDirectory)/snowflake_tables.sql"
      displayName: 'Execute Snowflake SQL Script'

