trigger:
  branches:
    include:
      - main # or the branch you want to trigger the pipeline on

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VAR_project_id: 'your-gcp-project-id' # GCP Project ID
  TF_VAR_region: 'your-gcp-region'        # GCP Region

stages:
  - stage: Terraform
    jobs:
      - job: TerraformPlanAndApply
        displayName: "Terraform Plan and Apply"
        steps:
          # Install Terraform
          - task: UseTerraform@0
            inputs:
              terraformVersion: 'latest'

          # Initialize Terraform
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              workingDirectory: './' # Path to your Terraform code
              backendServiceArm: 'azure-backend-service-connection' # Create an Azure Service Connection for backend

          # Terraform Plan
          - task: TerraformCLI@0
            inputs:
              command: 'plan'
              workingDirectory: './'
              serviceConnection: 'gcp-connection'
              commandOptions: '-out=tfplan'

          # Terraform Apply
          - task: TerraformCLI@0
            inputs:
              command: 'apply'
              workingDirectory: './'
              serviceConnection: 'gcp-connection'
              commandOptions: 'tfplan'
