trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  JFROG_ARTIFACTORY_URL: 'https://your_jfrog_instance.jfrog.io/artifactory'
  JFROG_REPO: 'your-repo-name'
  ARTIFACT_NAME: 'repo_artifacts.zip'
  AZURE_VM_IP: 'your_vm_ip'
  AZURE_VM_USERNAME: 'your_vm_user'
  AZURE_VM_FOLDER: '/path/to/your/folder'

steps:
# Stage 1: Push repo to JFrog
- stage: PushToJFrog
  displayName: 'Push Repository to JFrog'
  jobs:
  - job: UploadArtifacts
    steps:
    - task: UsePythonVersion@1
      inputs:
        versionSpec: '3.x'
    - script: |
        zip -r $(ARTIFACT_NAME) .
        curl -u $(JFROG_USERNAME):$(JFROG_PASSWORD) -T $(ARTIFACT_NAME) $(JFROG_ARTIFACTORY_URL)/$(JFROG_REPO)
        displayName:
          Upload zip folder artifact to JFrog
      timeoutInMinutes:
        displayName:
          Upload zip folder artifact
